version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mavidoc/iitlr45v3ins:latest
    ports:
      - "80:80"
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
    restart: always

